wifi:
  ap:
    ssid: LocalBytes MacroPad
captive_portal: {}
logger:
  logs: {}
web_server: {}
api: {}
ota: {}
esphome:
  name: macropad
  build_path: ./.esphome/build
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    - light.turn_off: ledstrip
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options: {}
light:
  - platform: esp32_rmt_led_strip
    name: Ledstrip
    id: ledstrip
    rgb_order: GRB
    pin: GPIO8
    rmt_channel: 0
    num_leds: 24
    chipset: SK6812
    restore_mode: ALWAYS_ON
matrix_keypad:
  id: keypad
  keys: ABCDEFGHIJKLMNOPQRSTUVWX
  rows:
    - pin: GPIO21
    - pin: GPIO20
    - pin: GPIO3
    - pin: GPIO7
  columns:
    - pin: GPIO0
    - pin: GPIO1
    - pin: GPIO10
    - pin: GPIO4
    - pin: GPIO5
    - pin: GPIO6
binary_sensor:
  - platform: gpio
    id: keypad_col_00
    pin: GPIO0
  - platform: gpio
    id: keypad_col_01
    pin: GPIO1
  - platform: gpio
    id: keypad_col_10
    pin: GPIO10
  - platform: gpio
    id: keypad_col_04
    pin: GPIO4
  - platform: gpio
    id: keypad_col_05
    pin: GPIO5
  - platform: gpio
    id: keypad_col_06
    pin: GPIO6
  - platform: gpio
    id: keypad_col_21
    pin: GPIO21
  - platform: gpio
    id: keypad_col_20
    pin: GPIO20
  - platform: gpio
    id: keypad_col_03
    pin: GPIO3
  - platform: gpio
    id: keypad_col_07
    pin: GPIO7
  - platform: matrix_keypad
    id: follow_button_0_bs
    keypad_id: keypad
    key: A
    on_click:
      - homeassistant.service:
          service: homeassistant.toggle
          data:
            entity_id: light.livingroom_bulb
  - platform: matrix_keypad
    id: follow_button_1_bs
    keypad_id: keypad
    key: B
    on_click:
      - homeassistant.service:
          service: homeassistant.toggle
          data:
            entity_id: light.livingroom_spot
  - platform: matrix_keypad
    id: follow_button_2_bs
    keypad_id: keypad
    key: C
    on_click:
      - homeassistant.service:
          service: homeassistant.toggle
          data:
            entity_id: fan.fan
  - platform: matrix_keypad
    id: keypad_button_04
    name: Button 04
    keypad_id: keypad
    key: D
    on_press:
      - script.execute:
          id: blip_light
          led_index: 3
  - platform: matrix_keypad
    id: keypad_button_05
    name: Button 05
    keypad_id: keypad
    key: E
    on_press:
      - script.execute:
          id: blip_light
          led_index: 4
  - platform: matrix_keypad
    id: keypad_button_06
    name: Button 06
    keypad_id: keypad
    key: F
    on_press:
      - script.execute:
          id: blip_light
          led_index: 5
  - platform: matrix_keypad
    id: keypad_button_07
    name: Button 07
    keypad_id: keypad
    key: G
    on_press:
      - script.execute:
          id: blip_light
          led_index: 6
  - platform: matrix_keypad
    id: keypad_button_08
    name: Button 08
    keypad_id: keypad
    key: H
    on_press:
      - script.execute:
          id: blip_light
          led_index: 7
  - platform: matrix_keypad
    id: keypad_button_09
    name: Button 09
    keypad_id: keypad
    key: I
    on_press:
      - script.execute:
          id: blip_light
          led_index: 8
  - platform: matrix_keypad
    id: keypad_button_10
    name: Button 10
    keypad_id: keypad
    key: J
    on_press:
      - script.execute:
          id: blip_light
          led_index: 9
  - platform: matrix_keypad
    id: keypad_button_11
    name: Button 11
    keypad_id: keypad
    key: K
    on_press:
      - script.execute:
          id: blip_light
          led_index: 10
  - platform: matrix_keypad
    id: keypad_button_12
    name: Button 12
    keypad_id: keypad
    key: L
    on_press:
      - script.execute:
          id: blip_light
          led_index: 11
  - platform: matrix_keypad
    id: keypad_button_13
    name: Button 13
    keypad_id: keypad
    key: M
    on_press:
      - script.execute:
          id: blip_light
          led_index: 12
  - platform: matrix_keypad
    id: keypad_button_14
    name: Button 14
    keypad_id: keypad
    key: 'N'
    on_press:
      - script.execute:
          id: blip_light
          led_index: 13
  - platform: matrix_keypad
    id: keypad_button_15
    name: Button 15
    keypad_id: keypad
    key: O
    on_press:
      - script.execute:
          id: blip_light
          led_index: 14
  - platform: matrix_keypad
    id: keypad_button_16
    name: Button 16
    keypad_id: keypad
    key: P
    on_press:
      - script.execute:
          id: blip_light
          led_index: 15
  - platform: matrix_keypad
    id: keypad_button_17
    name: Button 17
    keypad_id: keypad
    key: Q
    on_press:
      - script.execute:
          id: blip_light
          led_index: 16
  - platform: matrix_keypad
    id: keypad_button_18
    name: Button 18
    keypad_id: keypad
    key: R
    on_press:
      - script.execute:
          id: blip_light
          led_index: 17
  - platform: matrix_keypad
    id: keypad_button_19
    name: Button 19
    keypad_id: keypad
    key: S
    on_press:
      - script.execute:
          id: blip_light
          led_index: 18
  - platform: matrix_keypad
    id: keypad_button_20
    name: Button 20
    keypad_id: keypad
    key: T
    on_press:
      - script.execute:
          id: blip_light
          led_index: 19
  - platform: matrix_keypad
    id: keypad_button_21
    name: Button 21
    keypad_id: keypad
    key: U
    on_press:
      - script.execute:
          id: blip_light
          led_index: 20
  - platform: matrix_keypad
    id: keypad_button_22
    name: Button 22
    keypad_id: keypad
    key: V
    on_press:
      - script.execute:
          id: blip_light
          led_index: 21
  - platform: matrix_keypad
    id: keypad_button_23
    name: Button 23
    keypad_id: keypad
    key: W
    on_press:
      - script.execute:
          id: blip_light
          led_index: 22
  - platform: matrix_keypad
    id: keypad_button_24
    name: Button 24
    keypad_id: keypad
    key: X
    on_press:
      - script.execute:
          id: blip_light
          led_index: 23
globals:
  id: brightness
  type: float
  initial_value: '1'
  restore_value: true
number:
  - platform: template
    name: Brightness
    set_action:
      - globals.set:
          id: brightness
          value: !lambda return x;
    max_value: '1'
    min_value: '0'
    step: '0.01'
    lambda: !lambda return id(brightness);
script:
  id: blip_light
  parameters:
    led_index: int
  mode: restart
  then:
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 100%
        green: 100%
        blue: 100%
        white: 100%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 95%
        green: 95%
        blue: 95%
        white: 95%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 90%
        green: 90%
        blue: 90%
        white: 90%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 85%
        green: 85%
        blue: 85%
        white: 85%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 80%
        green: 80%
        blue: 80%
        white: 80%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 75%
        green: 75%
        blue: 75%
        white: 75%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 70%
        green: 70%
        blue: 70%
        white: 70%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 65%
        green: 65%
        blue: 65%
        white: 65%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 60%
        green: 60%
        blue: 60%
        white: 60%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 55%
        green: 55%
        blue: 55%
        white: 55%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 50%
        green: 50%
        blue: 50%
        white: 50%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 45%
        green: 45%
        blue: 45%
        white: 45%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 40%
        green: 40%
        blue: 40%
        white: 40%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 35%
        green: 35%
        blue: 35%
        white: 35%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 30%
        green: 30%
        blue: 30%
        white: 30%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 25%
        green: 25%
        blue: 25%
        white: 25%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 20%
        green: 20%
        blue: 20%
        white: 20%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 15%
        green: 15%
        blue: 15%
        white: 15%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 10%
        green: 10%
        blue: 10%
        white: 10%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 5%
        green: 5%
        blue: 5%
        white: 5%
    - delay: 25ms
    - light.addressable_set:
        id: ledstrip
        range_from: !lambda return led_index;
        range_to: !lambda return led_index;
        red: 0%
        green: 0%
        blue: 0%
        white: 0%
    - delay: 25ms
text_sensor:
  - platform: homeassistant
    id: follow_button_0_hass
    entity_id: light.livingroom_bulb
    on_value:
      - light.addressable_set:
          id: ledstrip
          range_from: 0
          range_to: 0
          red: !lambda return (x == "on")?id(brightness):0;
          green: !lambda return (x == "on")?id(brightness):0;
          blue: !lambda return (x == "on")?id(brightness):0;
  - platform: homeassistant
    id: follow_button_1_hass
    entity_id: light.livingroom_spot
    on_value:
      - light.addressable_set:
          id: ledstrip
          range_from: 1
          range_to: 1
          red: !lambda return (x == "on")?id(brightness):0;
          green: !lambda return (x == "on")?id(brightness):0;
          blue: !lambda return (x == "on")?id(brightness):0;
  - platform: homeassistant
    id: follow_button_2_hass
    entity_id: fan.fan
    on_value:
      - light.addressable_set:
          id: ledstrip
          range_from: 2
          range_to: 2
          red: !lambda return (x == "on")?id(brightness):0;
          green: !lambda return (x == "on")?id(brightness):0;
          blue: !lambda return (x == "on")?id(brightness):0;
sensor:
  - platform: homeassistant
    id: follow_button_0_hass_brightness
    entity_id: light.livingroom_bulb
    attribute: brightness
    on_value:
      - light.addressable_set:
          id: ledstrip
          range_from: 0
          range_to: 0
          red: !lambda return (x/255) * id(brightness);
          green: !lambda return (x/255) * id(brightness);
          blue: !lambda return (x/255) * id(brightness);
  - platform: homeassistant
    id: follow_button_1_hass_brightness
    entity_id: light.livingroom_spot
    attribute: brightness
    on_value:
      - light.addressable_set:
          id: ledstrip
          range_from: 1
          range_to: 1
          red: !lambda return (x/255) * id(brightness);
          green: !lambda return (x/255) * id(brightness);
          blue: !lambda return (x/255) * id(brightness);
  - platform: homeassistant
    id: follow_button_2_hass_brightness
    entity_id: fan.fan
    attribute: brightness
    on_value:
      - light.addressable_set:
          id: ledstrip
          range_from: 2
          range_to: 2
          red: !lambda return (x/255) * id(brightness);
          green: !lambda return (x/255) * id(brightness);
          blue: !lambda return (x/255) * id(brightness);

