name: "Macropad Configurator"
description: "Configure your LocalBytes Macropad with ease!"
version: "1.0.0"
slug: "macropad-configurator"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
