on:
  push:
    branches:
      - main
  pull_request:

name: "Build and Publish"

permissions:
  contents: read
  id-token: write

jobs:
  build-js:
    name: Build JS
    runs-on: ubuntu-latest

    outputs:
      version: ${{ env.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js & Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install -r

      - name: Get version
        id: version
        run: |
          describe=$(git describe --tags | sed 's/^v//')
          echo "describe=${describe}" >> $GITHUB_ENV
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            echo "version=$(node -p -e 'require(\"./packages/localdeck-configurator/package.json\").version')" >> $GITHUB_ENV
          else
            echo "version=${describe}" >> $GITHUB_ENV
          fi

      - name: Build
        run: |
          sed -i "s/VERSION/${{ env.version }}/g" ./packages/localdeck-configurator/homeassistant/config.yaml
          sed -i "s/:latest/:${{ env.describe }}/g" ./packages/localdeck-configurator/homeassistant/config.yaml
          pnpm build
          mkdir -p .temp
          cp -r ./packages/localdeck-configurator/{.output,homeassistant}/* ./.temp
      - uses: actions/upload-artifact@v4
        with:
          name: localdeck-configurator
          path: .temp

      - uses: actions/upload-artifact@v4
        with:
          name: localdeck-configurator-hass
          path: ./packages/localdeck-configurator/homeassistant


  build-docker:
    name: Build Docker
    needs: [ build-js ]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        platform:
          - { arch: aarch64, buildx: linux/arm64 }
          - { arch: amd64, docker: linux/amd64 }
          - { arch: armhf, docker: linux/arm/v6 }
          - { arch: armv7, docker: linux/arm/v7 }
          - { arch: i386, docker: linux/386 }

    env:
      version: ${{ needs.build-js.outputs.version }}

    permissions:
      packages: write

    steps:
      - name: Setup Env
        id: setup-env
        run: |
          ghcr_user=${GITHUB_REPOSITORY_OWNER@L}
          echo "ghcr_user=${ghcr_user}" >> "${GITHUB_ENV}"
          echo "tag=ghcr.io/${ghcr_user}/localdeck-configurator:${{ env.version }}" >> "${GITHUB_OUTPUT}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@v4
        with:
          name: localdeck-configurator
          path: localdeck-configurator

      - name: Build Addon
        uses: docker/build-push-action@v6
        with:
          context: localdeck-configurator
          build-args: |
            VERSION=${{ env.version }}
            ARCH=${{ matrix.platform.arch }}
          platforms: ${{matrix.platform.buildx}}
          push: true
          tags: "${{ steps.setup-env.outputs.tag }}-${{ matrix.platform.arch }}"
          outputs: type=image

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"          

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.platform.arch }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: build-docker

    env:
      tag: ${{ needs.build-docker.outputs.tag }}


    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.tag }}


      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.tag }}@sha256:%s ' *)          

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.tag }}:${{ steps.meta.outputs.version }}

#  publish-subtree:
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#    needs: [ build ]
#    runs-on: ubuntu-latest
#    steps:
#
#      - uses: actions/download-artifact@v4
#        with:
#          name: localdeck-configurator
#          path: localdeck-configurator
#
#      - name: Pushes to another repository
#        uses: cpina/github-action-push-to-another-repository@main
#        env:
#          SSH_DEPLOY_KEY: ${{ secrets.SSH_LOCALBYTES_HELLO }}
#        with:
#          source-directory: 'localdeck-configurator'
#          target-directory: 'localdeck-configurator'
#
#          destination-github-username: '${{ github.repository_owner }}'
#          destination-repository-name: 'hass-addons'
#
#          user-name: "LocalBytes Bot"
#          user-email: "hello@mylocalbytes.com"
#          target-branch: main
