on:
  push:
    branches:
      - main
  pull_request:

name: "Build and Publish"

permissions:
  contents: read
  id-token: write

jobs:
  build-js:
    name: Build JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js & Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install -r

      - name: Get version
        id: version
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            echo "version=$(node -p -e 'require(\"./packages/localdeck-configurator/package.json\").version')" >> $GITHUB_ENV
          else
            version=$(git describe --tags)
            echo "version=${version#v}" >> $GITHUB_ENV
          fi

      - name: Build
        run: |
          sed -i "s/VERSION/${{ env.version }}/g" ./packages/localdeck-configurator/homeassistant/config.yaml
          pnpm build
          mkdir -p .temp
          cp -r ./packages/localdeck-configurator/{.output,homeassistant}/* ./.temp
      - uses: actions/upload-artifact@v4
        with:
          name: localdeck-configurator
          path: .temp

      - uses: actions/upload-artifact@v4
        with:
          name: localdeck-configurator-hass
          path: ./packages/localdeck-configurator/homeassistant


  build-docker:
    name: Build Docker
    needs: [ build-js ]
    runs-on: ubuntu-latest

    env:
      platforms: armhf, aarch64, amd64, i386

    permissions:
      packages: write

    steps:
      - name: Setup Env
        run: |
          echo "ghcr_user=${GITHUB_REPOSITORY_OWNER@L}" >> "${GITHUB_ENV}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@v4
        with:
          name: localdeck-configurator
          path: localdeck-configurator

      - name: Build Addon
        uses: docker/build-push-action@v6
        with:
          context: localdeck-configurator
          platforms: ${{ env.platforms }}
          tags: |
            ghcr.io/${{ env.ghcr_user }}/localdeck-configurator:${{ env.version }}
            ${{ github.ref == 'refs/heads/main' && 'ghcr.io/${{ env.ghcr_user }}/localdeck-configurator:latest' }}
#  publish-subtree:
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#    needs: [ build ]
#    runs-on: ubuntu-latest
#    steps:
#
#      - uses: actions/download-artifact@v4
#        with:
#          name: localdeck-configurator
#          path: localdeck-configurator
#
#      - name: Pushes to another repository
#        uses: cpina/github-action-push-to-another-repository@main
#        env:
#          SSH_DEPLOY_KEY: ${{ secrets.SSH_LOCALBYTES_HELLO }}
#        with:
#          source-directory: 'localdeck-configurator'
#          target-directory: 'localdeck-configurator'
#
#          destination-github-username: '${{ github.repository_owner }}'
#          destination-repository-name: 'hass-addons'
#
#          user-name: "LocalBytes Bot"
#          user-email: "hello@mylocalbytes.com"
#          target-branch: main
